### ISSUE TITLE
Safari IOS doesn't allow connection to metamask mobile

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#27]
**Bug Description**

Described with video here:

https://discord.com/channels/892662024469884939/892662024469884942/903869548778885120

**Comment by kasumi-1** [comment]
$400 MIST bounty (check #bounties in https://discord.gg/mistswapdex)

**Comment by mainnet-pat** [comment]
To my knowledge Safari does not support Web3 at all, neither Mobile nor Desktop.
I guess it is the expected behaviour and not an issue.

**Comment by kasumi-1** [comment]
Referenced in #41 with solution
