### ISSUE TITLE
add link to liquidity pair from pool dropdown in farm page

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#44]
**Is your feature request related to a problem? Please describe.**
Provide a quick way to navigate add additional liquidity to a farm.

**Describe the solution you'd like**
Show link back to liquidity add page on the farm dropdown.

**Additional context**
requested by sploit, who likes this feature on benswap.

**Comment by mainnet-pat** [comment]
claim

**Comment by mainnet-pat** [comment]
Can be closed
