### ISSUE TITLE
Add APR to bar / staking page

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#47]
on this pic, besides the "view stats" is basically something like "Current APR: X%"

![image](https://user-images.githubusercontent.com/90275229/141435048-b22405da-bc9b-4b0b-b449-917a19800851.png)

**Comment by kasumi-1** [comment]
$200 MIST bounty (check #bounties in https://discord.gg/mistswapdex)

**Comment by yqz0203** [comment]
claim.

**Comment by kasumi-1** [comment]
@yqz0203 have you started on this already? @mainnet-pat just sent pr that partially completes this.

**Comment by yqz0203** [comment]
> @yqz0203 have you started on this already? @mainnet-pat just sent pr that partially completes this.

I just finished it. 😂

**Comment by kasumi-1** [comment]
@yqz0203 ok can you send PR will credit
