### ISSUE TITLE
Add light color scheme mode 

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#50]
**Is your feature request related to a problem? Please describe.**

User prefers light mode over dark mode as it's easier on their eyes.

**Describe the solution you'd like**

A toggle somewhere to switch it, that remembers what you've selected.

**Comment by kasumi-1** [comment]
Must actually look nice and be fully themed.

$500 MIST bounty (check #bounties in https://discord.gg/mistswapdex)

**Comment by yqz0203** [comment]
claim
