### ISSUE TITLE
"Price impact too High" warning shouldn't take precedence over approval button on swap page

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#59]
**Bug Description**
If price impact too high, the approve button will be invisible, not allowing you to swap.

**Comment by kasumi-1** [comment]
$100 MIST bounty (check #bounties in https://discord.gg/mistswapdex) please write CLAIM here and submit PR within 1 day of claiming - if task is not completed within 1 day of claiming another user may claim to finish.

**Comment by mainnet-pat** [comment]
claim
