### ISSUE TITLE
On very small screens you cannot scroll on swap page to see button

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#69]
**Bug Description**
User on older iphone was unable to use swap page because there was no way to scroll down.

**Comment by kasumi-1** [comment]
$200 MIST bounty (check #bounties in https://discord.gg/mistswapdex) please write CLAIM here and submit PR within 1 day of claiming - if task is not completed within 1 day of claiming another user may claim to finish.

**Comment by yqz0203** [comment]
claim
