### ISSUE TITLE
Add button to add smartbch network

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#8]
**Is your feature request related to a problem? Please describe.**
There should be an easy way to add smartbch, maybe from the wrong network modal. 

**Describe the solution you'd like**
A button to add to metamask (if selected wallet).

**Describe alternatives you've considered**
Do nothing.

**Comment by mainnet-pat** [comment]
Can I steal this task?

**Comment by kasumi-1** [comment]
@mainnet-pat yes, I think webeli is busy now.
