### ISSUE TITLE
Enable additional wallet types

### ISSUE THREAD

**Issue by kasumi-1** [mistswapdex/mistswap-interface#81]
other swaps allow TrustWallet, MathWallet, TokenPocket, WalletConnect, etc.
I use walletconnect + imToken wallet and am able to create a custom wallet and use it on other SmartBCH swaps

**Comment by Maria888888** [comment]
Does anyone understand imtoken mining?

**Comment by kasumi-1** [comment]
This is fixed with c89baa97d6e4d14adbf40e1f87c2c7eeebc92c3e
